export enum StudentDocumentType {
  PHOTO = 'PHOTO',
  BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE',
  MEDICAL_CERTIFICATE = 'MEDICAL_CERTIFICATE',
  VACCINATION_CARD = 'VACCINATION_CARD',
  ID_CARD = 'ID_CARD',
  EMPLOYMENT_CONTRACT = 'EMPLOYMENT_CONTRACT',
  DIPLOMA = 'DIPLOMA',
  REGISTRATION_FORM = 'REGISTRATION_FORM',
  OTHER = 'OTHER',
}
